### ISSUE TITLE
[Tenant OPAI] Device api format problem

### ISSUE THREAD

**Issue by zack9433** [MOXA-ISD/oapi-doc#10]
這是我的提案

```
{
  "tenantId": "65af94c4-07e4-43d7-abad-3cb5f295550b",
  "uuid": "4b4f1ab2-18ac-483e-aedd-2aaeb2dabd59",
  "group": "MOXA-ISD",
  "modal": "Modal-1",
  "type": "IIoT Gateway",
  "status": "online",
  "firmwareVersion": "1.0.0",
  "configVersion": "1.0.0",
  "reportedProperties": [
    {
      "id": 1,
      "type": "systemTime",
      "name": "date",
      "description": "xxxx",
      "value": ""
    },
    {
      "id": 2,
      "type": "systemTime",
      "name": "timeZone",
      "description": "xxxx",
      "value": ""
    },
    {
      "id": 3,
      "type": "systemTime",
      "name": "ntpEnable",
      "description": "xxxx",
      "value": ""
    },
    {
      "id": 4,
      "type": "systemTime",
      "name": "timeServer",
      "description": "xxxx",
      "value": ""
    },
    {
      "id": 5,
      "type": "systemTime",
      "name": "poolInterval",
      "description": "xxxx",
      "value": ""
    },
    {
      "id": 6,
      "type": "systemTime",
      "name": "poolInterval",
      "description": "xxxx",
      "value": ""
    },
    {
      "id": 7,
      "type": "network",
      "name": "eth0",
      "description": "xxxx",
      "value": [
        {
          "id": 1,
          "name": "ipAddress",
          "description": "xxxx",
          "value": "192.168.3.21"
        },
        {
          "id": 2,
          "name": "mask",
          "description": "xxxx",
          "value": "255.255.255.0"
        },
        {
          "id": 3,
          "name": "gateway",
          "description": "xxxx",
          "value": "192.168.3.254"
        },
        {
          "id": 4,
          "name": "dhcp",
          "description": "xxxx",
          "value": true
        },
        {
          "id": 5,
          "name": "primaryDns",
          "description": "xxxx",
          "value": "192.168.3.254"
        },
        {
          "id": 6,
          "name": "secondaryDns",
          "description": "xxxx",
          "vaule": "10.29.11.121"
        }
      ]
    },
    {
      "id": 7,
      "type": "location",
      "name": "gps",
      "description": "xxxx",
      "value": [
        {
          "id": 1,
          "name": "manualLatitude",
          "description": "xxxx",
          "value": 24.5533998
        },
        {
          "id": 2,
          "name": "manualLongitude",
          "description": "xxxx",
          "value": 122.4488993
        }
      ]
    },
    {
      "id": 8,
      "type": "location",
      "name": "system",
      "description": "xxxx",
      "value": "WGS-84/GCJ-02"
    },
    {
      "id": 9,
      "type": "connection",
      "name": "status",
      "description": "xxxx",
      "value": "online"
    },
    {
      "id": 10,
      "type": "general",
      "name": "deviceName",
      "description": "xxxx",
      "value": "My Name"
    },
    {
      "id": 11,
      "type": "general",
      "name": "firmwareVersion",
      "description": "xxxx",
      "value": "1.0.0"
    },
    {
      "id": 12,
      "type": "general",
      "name": "edgeVersion",
      "description": "xxxx",
      "value": "1.0.0"
    },
    {
      "id": 13,
      "type": "general",
      "name": "configVersion",
      "description": "xxxx",
      "value": "1.0.0"
    }
  ],
  "desiredProperties": [
    {
      "id": 1,
      "type": "systemTime",
      "name": "date",
      "description": "xxxx",
      "value": ""
    },
    {
      "id": 2,
      "type": "systemTime",
      "name": "timeZone",
      "description": "xxxx",
      "value": ""
    },
    {
      "id": 3,
      "type": "systemTime",
      "name": "ntpEnable",
      "description": "xxxx",
      "value": ""
    },
    {
      "id": 4,
      "type": "systemTime",
      "name": "timeServer",
      "description": "xxxx",
      "value": ""
    },
    {
      "id": 5,
      "type": "systemTime",
      "name": "poolInterval",
      "description": "xxxx",
      "value": ""
    },
    {
      "id": 6,
      "type": "systemTime",
      "name": "poolInterval",
      "description": "xxxx",
      "value": ""
    },
    {
      "id": 7,
      "type": "network",
      "name": "eth0",
      "description": "xxxx",
      "value": [
        {
          "id": 1,
          "name": "ipAddress",
          "description": "xxxx",
          "value": "192.168.3.21"
        },
        {
          "id": 2,
          "name": "mask",
          "description": "xxxx",
          "value": "255.255.255.0"
        },
        {
          "id": 3,
          "name": "gateway",
          "description": "xxxx",
          "value": "192.168.3.254"
        },
        {
          "id": 4,
          "name": "dhcp",
          "description": "xxxx",
          "value": true
        },
        {
          "id": 5,
          "name": "primaryDns",
          "description": "xxxx",
          "value": "192.168.3.254"
        },
        {
          "id": 6,
          "name": "secondaryDns",
          "description": "xxxx",
          "vaule": "10.29.11.121"
        }
      ]
    },
    {
      "id": 7,
      "type": "location",
      "name": "gps",
      "description": "xxxx",
      "value": [
        {
          "id": 1,
          "name": "manualLatitude",
          "description": "xxxx",
          "value": 24.5533998
        },
        {
          "id": 2,
          "name": "manualLongitude",
          "description": "xxxx",
          "value": 122.4488993
        }
      ]
    },
    {
      "id": 8,
      "type": "location",
      "name": "system",
      "description": "xxxx",
      "value": "WGS-84/GCJ-02"
    },
    {
      "id": 9,
      "type": "connection",
      "name": "status",
      "description": "xxxx",
      "value": "online"
    },
    {
      "id": 10,
      "type": "general",
      "name": "deviceName",
      "description": "xxxx",
      "value": "My Name"
    },
    {
      "id": 11,
      "type": "general",
      "name": "firmwareVersion",
      "description": "xxxx",
      "value": "1.0.0"
    },
    {
      "id": 12,
      "type": "general",
      "name": "edgeVersion",
      "description": "xxxx",
      "value": "1.0.0"
    },
    {
      "id": 13,
      "type": "general",
      "name": "configVersion",
      "description": "xxxx",
      "value": "1.0.0"
    }
  ],
  "reportedLastUpdatedAt": "2018-08-12T20:17:46.384Z",
  "desiredLastUpdatedAt": "2018-08-12T20:17:46.384Z",
  "createdAt": "2018-08-12T20:17:46.384Z",
  "updatedAt": "2018-08-12T20:17:46.384Z"
}
```

**Comment by KevinKao809** [comment]
Zack, Owen and Cain,

有些欄位重複出現, 我依據目前 Table 欄位重新區分, 如下:

另外, Phase 2, Edge 只會送出 General 的 Properties, 不會有 Network. FYI.

此外, 這些內容, 除了 Restful API 會回傳外, Reported Properties 也會出現在 SignalR 的 Payload. (Refer to next comments).

{
    "tenantId": "65af94c4-07e4-43d7-abad-3cb5f295550b",
    "deviceUUID": "4b4f1ab2-18ac-483e-aedd-2aaeb2dabd59",
    "group": "MOXA-ISD",
    "modelName": "UC-8112-LX-CG",
    "deviceType": "IIoT Gateway",
    "connectionStatus": "online",
    "allowConnection": true,
    "imageURL": "http://123.456.net/xxx/xxx.jpg",
    "logoURL": "http://123.456.net/xxx/xxx.jpg",
    "lastRebootTime": "2018-08-12T20:17:46.384Z",
    "lastRebootReason": "Remote Reboot on ThingsPro Server by XXX",
    "reportedProperties": [      
      {
        "id": 1,
        "type": "general",
        "name": "deviceName",
        "description": "Device Name",
        "value": "Demo Device 01"
      },
      {
        "id": 2,
        "type": "general",
        "name": "firmwareVersion",
        "description": "Firmware Version",
        "value": "1.8.1"
      },      
      {
        "id": 3,
        "type": "general",
        "name": "configVersion",
        "description": "Config Version",
        "value": "3.1.2"
      },
      {
        "id": 4,
        "type": "network",
        "name": "eth0",
        "description": "Ethernet 0",
        "value": [
          {
            "id": 1,
            "name": "ipAddress",
            "description": "IP Address",
            "value": "192.168.3.21"
          },
          {
            "id": 2,
            "name": "mask",
            "description": "Subnet Mask",
            "value": "255.255.255.0"
          },
          {
            "id": 3,
            "name": "gateway",
            "description": "Default Gateway",
            "value": "192.168.3.254"
          },
          {
            "id": 4,
            "name": "dhcp",
            "description": "DHCP",
            "value": true
          },
          {
            "id": 5,
            "name": "primaryDns",
            "description": "Primary DNS",
            "value": "192.168.3.254"
          },
          {
            "id": 6,
            "name": "secondaryDns",
            "description": "Secondary DNS",
            "vaule": "10.29.11.121"
          }
        ]
      }
    ],
    "desiredProperties": [        
      {
        "id": 1,
        "type": "general",
        "name": "deviceName",
        "description": "Device Name",
        "value": "Demo Device 01"
      },
      {
        "id": 2,
        "type": "general",
        "name": "firmwareVersion",
        "description": "Firmware Version",
        "value": "1.8.1"
      },      
      {
        "id": 3,
        "type": "general",
        "name": "configVersion",
        "description": "Config Version",
        "value": "3.1.2"
      },
      {
        "id": 4,
        "type": "network",
        "name": "eth0",
        "description": "Ethernet 0",
        "value": [
          {
            "id": 1,
            "name": "ipAddress",
            "description": "IP Address",
            "value": "192.168.3.21"
          },
          {
            "id": 2,
            "name": "mask",
            "description": "Subnet Mask",
            "value": "255.255.255.0"
          },
          {
            "id": 3,
            "name": "gateway",
            "description": "Default Gateway",
            "value": "192.168.3.254"
          },
          {
            "id": 4,
            "name": "dhcp",
            "description": "DHCP",
            "value": true
          },
          {
            "id": 5,
            "name": "primaryDns",
            "description": "Primary DNS",
            "value": "192.168.3.254"
          },
          {
            "id": 6,
            "name": "secondaryDns",
            "description": "Secondary DNS",
            "vaule": "10.29.11.121"
          }
        ]
      }          
    ],
    "reportedLastUpdatedAt": "2018-08-12T20:17:46.384Z",
    "desiredLastUpdatedAt": "2018-08-12T20:17:46.384Z",
    "createdAt": "2018-08-12T20:17:46.384Z",
    "updatedAt": "2018-08-12T20:17:46.384Z"
  }

**Comment by KevinKao809** [comment]
Zack, SignalR 裡, 會主動提供 SystemProperties 更新的資料, payload 如下:

{
    "tenantId": "65af94c4-07e4-43d7-abad-3cb5f295550b",
    "deviceUUID": "4b4f1ab2-18ac-483e-aedd-2aaeb2dabd59",
    "dataSource": "systemProperties",
    "group": "MOXA-ISD",
    "connectionStatus": "online",
    "allowConnection": true,
    "lastRebootTime": "2018-08-12T20:17:46.384Z",
    "lastRebootReason": "Remote Reboot on ThingsPro Server by XXX",
    "reportedProperties": [      
      {
        "id": 1,
        "type": "general",
        "name": "deviceName",
        "description": "Device Name",
        "value": "Demo Device 01"
      },
      {
        "id": 2,
        "type": "general",
        "name": "firmwareVersion",
        "description": "Firmware Version",
        "value": "1.8.1"
      },      
      {
        "id": 3,
        "type": "general",
        "name": "configVersion",
        "description": "Config Version",
        "value": "3.1.2"
      },
      {
        "id": 4,
        "type": "network",
        "name": "eth0",
        "description": "Ethernet 0",
        "value": [
          {
            "id": 1,
            "name": "ipAddress",
            "description": "IP Address",
            "value": "192.168.3.21"
          },
          {
            "id": 2,
            "name": "mask",
            "description": "Subnet Mask",
            "value": "255.255.255.0"
          },
          {
            "id": 3,
            "name": "gateway",
            "description": "Default Gateway",
            "value": "192.168.3.254"
          },
          {
            "id": 4,
            "name": "dhcp",
            "description": "DHCP",
            "value": true
          },
          {
            "id": 5,
            "name": "primaryDns",
            "description": "Primary DNS",
            "value": "192.168.3.254"
          },
          {
            "id": 6,
            "name": "secondaryDns",
            "description": "Secondary DNS",
            "vaule": "10.29.11.121"
          }
        ]
      }
    ]
  }

**Comment by KevinKao809** [comment]
1. 修正 group => deviceGroup, 以及他會是 Array
2. 拆分 Desired and Reported Properties 到其他 EndPoint
3. SignalR device systemProperties 加入 reportedLastUpdatedAt 欄位.
[DevicePayloadSpec.zip](https://github.com/MOXA-ISD/oapi-doc/files/2344168/DevicePayloadSpec.zip)
