### ISSUE TITLE
[Tenant] System tag payload from Signalr

### ISSUE THREAD

**Issue by zack9433** [MOXA-ISD/oapi-doc#11]
```json
{
  "deviceUUID": "7dc73055-2ad9-4fdc-96d6-c9d18582ce01",
  "dataSource": "systemTag",
  "messageTimeStamp": "2018-08-29T01:52:45.6888512Z",
  "cpuUsage": {
    "unit": "%",
    "latest": {
      "value": 10,
      "updateTimeStamp": "2018-08-21T00:07:43.888Z"
    },
    "values": [
      { "value": 10, "updateTimeStamp": "2018-08-21T00:07:43.888Z" },
      { "value": 12, "updateTimeStamp": "2018-08-21T00:07:22.888Z" },
      { "value": 8, "updateTimeStamp": "2018-08-21T00:07:18.888Z" },
      { "value": 35, "updateTimeStamp": "2018-08-21T00:07:56.888Z" }
    ]
  },
  "memoryUsage": {
    "unit": "%",
    "total": 1000,
    "latest": {
      "value": 8,
      "updateTimeStamp": "2018-08-21T00:07:43.888Z"
    },
    "values": [
      { "value": 8, "updateTimeStamp": "2018-08-21T00:07:18.888Z" },
      { "value": 35, "updateTimeStamp": "2018-08-21T00:07:56.888Z" }
    ]
  },
  "gps": {
    "latitude": {
      "unit": "",
      "latest": {
        "value": 8,
        "updateTimeStamp": "2018-08-21T00:07:43.888Z"
      },
      "values": [
        { "value": 8, "updateTimeStamp": "2018-08-21T00:07:18.888Z" },
        { "value": 35, "updateTimeStamp": "2018-08-21T00:07:56.888Z" }
      ]
    },
    "longitude": {
      "unit": "",
      "latest": {
        "value": 8,
        "updateTimeStamp": "2018-08-21T00:07:43.888Z"
      },
      "values": [
        { "value": 8, "updateTimeStamp": "2018-08-21T00:07:18.888Z" },
        { "value": 35, "updateTimeStamp": "2018-08-21T00:07:56.888Z" }
      ]
    }
  },
  "wifi": [
    {
      "id": 1,
      "name": "wwan0",
      "signal": {
        "unit": "dB",
        "latest": {
          "value": 8,
          "updateTimeStamp": "2018-08-21T00:07:43.888Z"
        },
        "values": [
          { "value": 8, "updateTimeStamp": "2018-08-21T00:07:18.888Z" },
          { "value": 35, "updateTimeStamp": "2018-08-21T00:07:56.888Z" }
        ]
      },
      "enable": {
        "latest": {
          "value": true,
          "updateTimeStamp": "2018-08-21T00:07:43.888Z"
        },
        "values": [
          { "value": true, "updateTimeStamp": "2018-08-21T00:07:18.888Z" },
          { "value": true, "updateTimeStamp": "2018-08-21T00:07:56.888Z" }
        ]
      }
    }
  ],
  "cellular": [
    {
      "id": 1,
      "name": "cellular0",
      "signal": {
        "unit": "dB",
        "latest": {
          "value": 8,
          "updateTimeStamp": "2018-08-21T00:07:43.888Z"
        },
        "values": [
          { "value": 8, "updateTimeStamp": "2018-08-21T00:07:18.888Z" },
          { "value": 35, "updateTimeStamp": "2018-08-21T00:07:56.888Z" }
        ]
      },
      "enable": {
        "latest": {
          "value": true,
          "updateTimeStamp": "2018-08-21T00:07:43.888Z"
        },
        "values": [
          { "value": true, "updateTimeStamp": "2018-08-21T00:07:18.888Z" },
          { "value": true, "updateTimeStamp": "2018-08-21T00:07:56.888Z" }
        ]
      }
    }
  ],
  "ethernet": [
    {
      "id": 1,
      "name": "eth0",
      "enable": {
        "latest": {
          "value": true,
          "updateTimeStamp": "2018-08-21T00:07:43.888Z"
        },
        "values": [
          { "value": true, "updateTimeStamp": "2018-08-21T00:07:18.888Z" },
          { "value": false, "updateTimeStamp": "2018-08-21T00:07:56.888Z" }
        ]
      }
    }
  ],
  "storageUsage": [
    {
      "id": 1,
      "name": "storage0",
      "size": {
        "unit": "MB",
        "total": 1000,
        "latest": {
          "value": 8,
          "updateTimeStamp": "2018-08-21T00:07:43.888Z"
        },
        "values": [
          { "value": 8, "updateTimeStamp": "2018-08-21T00:07:18.888Z" },
          { "value": 35, "updateTimeStamp": "2018-08-21T00:07:56.888Z" }
        ]
      }
    }
  ]
}
```

**Comment by KevinKao809** [comment]
Zack, System Tag Payload on Signal R 沒太大問題, 只修正了 memoryUsage 裡的 TotalSize. 

目前 Phase 2.1, Edge Team 會送出來的只有 cpuUsage 以及 memoryUsage. FYI.

{
  "deviceUUID": "7dc73055-2ad9-4fdc-96d6-c9d18582ce01",
  "dataSource": "systemTag",
  "messageTimeStamp": "2018-08-29T01:52:45.6888512Z",
  "cpuUsage": {
    "unit": "%",
    "latest": {
      "value": 10,
      "updateTimeStamp": "2018-08-21T00:07:43.888Z"
    },
    "values": [
      { "value": 10, "updateTimeStamp": "2018-08-21T00:07:43.888Z" },
      { "value": 12, "updateTimeStamp": "2018-08-21T00:07:22.888Z" },
      { "value": 8, "updateTimeStamp": "2018-08-21T00:07:18.888Z" },
      { "value": 35, "updateTimeStamp": "2018-08-21T00:07:56.888Z" }
    ]
  },
  "memoryUsage": {
    "unit": "%",    
    "latest": {
      "value": 8,
      "updateTimeStamp": "2018-08-21T00:07:43.888Z"
    },
    "values": [
      { "value": 8, "updateTimeStamp": "2018-08-21T00:07:18.888Z" },
      { "value": 35, "updateTimeStamp": "2018-08-21T00:07:56.888Z" }
    ],
    "totalSize": {
        "size": 1024,
        "unit": "MB"
    }
  },
  "gps": {
    "latitude": {
      "unit": "",
      "latest": {
        "value": 8,
        "updateTimeStamp": "2018-08-21T00:07:43.888Z"
      },
      "values": [
        { "value": 8, "updateTimeStamp": "2018-08-21T00:07:18.888Z" },
        { "value": 35, "updateTimeStamp": "2018-08-21T00:07:56.888Z" }
      ]
    },
    "longitude": {
      "unit": "",
      "latest": {
        "value": 8,
        "updateTimeStamp": "2018-08-21T00:07:43.888Z"
      },
      "values": [
        { "value": 8, "updateTimeStamp": "2018-08-21T00:07:18.888Z" },
        { "value": 35, "updateTimeStamp": "2018-08-21T00:07:56.888Z" }
      ]
    }
  },
  "wifi": [
    {
      "id": 1,
      "name": "wan0",
      "signal": {
        "unit": "dB",
        "latest": {
          "value": 8,
          "updateTimeStamp": "2018-08-21T00:07:43.888Z"
        },
        "values": [
          { "value": 8, "updateTimeStamp": "2018-08-21T00:07:18.888Z" },
          { "value": 35, "updateTimeStamp": "2018-08-21T00:07:56.888Z" }
        ]
      },
      "enable": {
        "latest": {
          "value": true,
          "updateTimeStamp": "2018-08-21T00:07:43.888Z"
        },
        "values": [
          { "value": true, "updateTimeStamp": "2018-08-21T00:07:18.888Z" },
          { "value": true, "updateTimeStamp": "2018-08-21T00:07:56.888Z" }
        ]
      }
    }
  ],
  "cellular": [
    {
      "id": 1,
      "name": "cellular0",
      "signal": {
        "unit": "dB",
        "latest": {
          "value": 8,
          "updateTimeStamp": "2018-08-21T00:07:43.888Z"
        },
        "values": [
          { "value": 8, "updateTimeStamp": "2018-08-21T00:07:18.888Z" },
          { "value": 35, "updateTimeStamp": "2018-08-21T00:07:56.888Z" }
        ]
      },
      "enable": {
        "latest": {
          "value": true,
          "updateTimeStamp": "2018-08-21T00:07:43.888Z"
        },
        "values": [
          { "value": true, "updateTimeStamp": "2018-08-21T00:07:18.888Z" },
          { "value": true, "updateTimeStamp": "2018-08-21T00:07:56.888Z" }
        ]
      }
    }
  ],
  "ethernet": [
    {
      "id": 1,
      "name": "eth0",
      "enable": {
        "latest": {
          "value": true,
          "updateTimeStamp": "2018-08-21T00:07:43.888Z"
        },
        "values": [
          { "value": true, "updateTimeStamp": "2018-08-21T00:07:18.888Z" },
          { "value": false, "updateTimeStamp": "2018-08-21T00:07:56.888Z" }
        ]
      }
    }
  ],
  "storageUsage": [
    {
      "id": 1,
      "name": "storage0",
      "size": {
        "unit": "MB",
        "total": 1000,
        "latest": {
          "value": 8,
          "updateTimeStamp": "2018-08-21T00:07:43.888Z"
        },
        "values": [
          { "value": 8, "updateTimeStamp": "2018-08-21T00:07:18.888Z" },
          { "value": 35, "updateTimeStamp": "2018-08-21T00:07:56.888Z" }
        ]
      }
    }
  ]
}

**Comment by zack9433** [comment]
@KevinKao809 收到

我後來覺得把 xxxUsage 的 Usage 拿掉好了
